# Site settings
title: opengl-tutorial
description: "Free tutorials for modern Opengl (3.3 and later) in C/C++"
baseurl: ""
highlighter: rouge
safe: true
lsi: false
source:      .
languages_iso: [en]
languages: [en]
languages_names: [english]
# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
