# Site settings
title: The Brain Nexus
url: "https://mdelsole.github.io/brain-nexus"
description: "A free resource for anything and everything about the human brain"
baseurl: ""
highlighter: rouge
safe: true
lsi: false
source:      .
languages_iso: [en]
languages: [en]
languages_names: [english]
# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
